### ISSUE TITLE
Fix button labels: 'All' is displayed regardless of selected question set

### ISSUE THREAD

**Issue by christophblessing** [christophblessing/quiz-recap#3]
The label on the button always reads 'all,' even when a complete set of questions is not selected.

![Screenshot 2024-02-09 at 14 26 36](https://github.com/christophblessing/quiz-recap/assets/22977799/694faa77-4e0c-4687-b748-85f8d9bf2ae0)

Possibly a regression from https://github.com/christophblessing/quiz-recap/pull/1

**Comment by JuliaCasamitjana** [comment]
Resolved in commit f86eaaa
